name: vpp-merge-make-test

on:
  workflow_dispatch:
    inputs:
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_PATCHSET_REVISION:
        description: "The revision sha"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string

env:
  GERRIT_BRANCH: ${{ inputs.GERRIT_BRANCH }}
  GERRIT_CHANGE_ID: ${{ inputs.GERRIT_CHANGE_ID }}
  GERRIT_CHANGE_NUMBER: ${{ inputs.GERRIT_CHANGE_NUMBER }}
  GERRIT_CHANGE_URL: ${{ inputs.GERRIT_CHANGE_URL }}
  GERRIT_EVENT_TYPE: ${{ inputs.GERRIT_EVENT_TYPE }}
  GERRIT_PATCHSET_NUMBER: ${{ inputs.GERRIT_PATCHSET_NUMBER }}
  GERRIT_PATCHSET_REVISION: ${{ inputs.GERRIT_PATCHSET_REVISION }}
  GERRIT_PROJECT: ${{ inputs.GERRIT_PROJECT }}
  GERRIT_REFSPEC: ${{ inputs.GERRIT_REFSPEC }}

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

jobs:
  vpp-merge-make-test:
    name: ${{ github.workflow }}-${{ inputs.GERRIT_BRANCH }}-${{ matrix.build_type }}-${{ matrix.os }}-${{ matrix.executor_arch }}
    if: ${{ inputs.GERRIT_EVENT_TYPE == 'change-merged' }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=builder
      - fdio:namespace=sandbox
      - fdio:os=${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu2404', 'ubuntu2204', 'debian12']
        executor_arch: ['x86_64', 'aarch64']
        build_type: ['rel']
        exclude:
          # Exclude debian12 on aarch64 for all builds
          - os: 'debian12'
            executor_arch: 'aarch64'

    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      CACHE_DATE: ${{ github.run_id }}
      CCACHE_DIR: /scratch/ccache/${{ matrix.os }}-${{ matrix.executor_arch }}
      MAKE_PARALLEL_JOBS: 16
      TEST_JOBS: 16
      TEST_RETRIES: 3
      MAKE_TEST_OS: ${{ matrix.os == 'ubuntu2204' && 'ubuntu-22.04' || 'ubuntu-24.04'  }}
      MAKE_TEST_MULTIWORKER_OS: 'debian-12'
      VPPAPIGEN_TEST_OS: ${{ matrix.os == 'ubuntu2204' && 'ubuntu-22.04' || 'ubuntu-24.04' }}
      SHM_SIZE: ${{ matrix.executor_arch == 'aarch64' && '4096M' || '2048M' }}
      WORKSPACE: ${{ github.workspace }}
      GERRIT_BRANCH: ""
      GERRIT_CHANGE_URL: ""
      GERRIT_PROJECT: ""
      GERRIT_REFSPEC: ""
      TUI_LINE: "*******************************************************************"

    steps:
      - name: Actions Checkout
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: pmikus/.github/.github/actions/setup-executor-env@main

      - name: Show Nomad Dockerfile
        uses: pmikus/.github/.github/actions/show-nomad-dockerfile@main

      - name: Gerrit Checkout
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/checkout-gerrit-change-action@54d751e8bd167bc91f7d665dabe33fae87aaaa63 # v0.9
        with:
          gerrit-refspec: ${{ env.GERRIT_REFSPEC }}
          gerrit-project: ${{ env.GERRIT_PROJECT }}
          gerrit-url: ${{ env.GERRIT_CHANGE_URL }}
          fetch-depth: 0
          delay: "0s"

      - name: Setup Docker VPP Runtime Environment for 'make test'
        uses: pmikus/vpp/.github/actions/vpp-docker-runtime-setup@master

      - name: Install VPP dependencies
        uses: pmikus/vpp/.github/actions/vpp-install-deps@master

      - name: Install VPP external dependencies
        uses: pmikus/vpp/.github/actions/vpp-install-ext-deps@master

      - name: Build VPP
        uses: pmikus/vpp/.github/actions/vpp-build@master
        with:
          MAKE_PARALLEL_JOBS: ${{ env.MAKE_PARALLEL_JOBS }}
          BUILD_TYPE: ${{ env.BUILD_TYPE }}

      - name: VPP Make Test
        uses: pmikus/vpp/.github/actions/vpp-make-test@master
        timeout-minutes: 75
        with:
          TEST_JOBS: ${{ env.TEST_JOBS }}
          MAKE_TEST_OS: ${{ env.MAKE_TEST_OS }}
          MAKE_TEST_MULTIWORKER_OS: ${{ env.MAKE_TEST_MULTIWORKER_OS }}
          VPPAPIGEN_TEST_OS: ${{ env.VPPAPIGEN_TEST_OS }}


