name: vpp-vfy-mktst

on:
  workflow_run:
    workflows: ["vpp-checkstyle"]
    types:
      - completed

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

concurrency:
  group: required-${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}-${{ github.event.workflow_run.id }}
  cancel-in-progress: true

jobs:
  vpp-vfy-mktst:
    name: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}-${{ matrix.build_type }}-${{ matrix.os }}-${{ matrix.executor_arch }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=builder
      - fdio:namespace=dev
      - fdio:os=${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu2404', 'ubuntu2204', 'debian12']
        executor_arch: ['x86_64', 'aarch64']
        build_type: ['dbg', 'rel']
        exclude:
          # Exclude debian12 on aarch64 for all builds
          - os: 'debian12'
            executor_arch: 'aarch64'
          # Exclude non-ubuntu2204 OS for debug builds
          - build_type: 'dbg'
            os: 'ubuntu2404'
          - build_type: 'dbg'
            os: 'debian12'
          # Exclude aarch64 architecture for debug builds
          - build_type: 'dbg'
            executor_arch: 'aarch64'

    env:
      WORKSPACE: /scratch/docker-build/vpp
      CCACHE_DIR: /scratch/ccache/${{ matrix.os }}-${{ matrix.executor_arch }}
      MAKE_PARALLEL_JOBS: 16
      TEST_JOBS: 16
      TEST_RETRIES: 3
      MAKE_TEST_OS: ${{ matrix.os == 'ubuntu2204' && 'ubuntu-22.04' || 'ubuntu-24.04'  }}
      MAKE_TEST_MULTIWORKER_OS: 'debian-12'
      VPPAPIGEN_TEST_OS: ${{ matrix.os == 'ubuntu2204' && 'ubuntu-22.04' || 'ubuntu-24.04' }}
      SHM_SIZE: ${{ matrix.executor_arch == 'aarch64' && '4096M' || '2048M' }}
      GERRIT_BRANCH: ""
      GERRIT_CHANGE_URL: ""
      GERRIT_PROJECT: ""
      GERRIT_REFSPEC: ""
      GERRIT_CHANGE_NUMBER: ""
      GERRIT_PATCHSET_NUMBER: ""
      TUI_LINE: "*******************************************************************"

    steps:
      - name: Actions Checkout
        uses: actions/checkout@v5

      - name: Setup Environment
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/setup-executor-env@b728d1589228e2891a4241a1bba362d76895c225

      - name: Show Nomad Dockerfile
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/show-nomad-dockerfile@b728d1589228e2891a4241a1bba362d76895c225

      - name: Restore VPP Gerrit Environment Variables
        # yamllint disable-line rule:line-length
        uses: pmikus/.github/.github/actions/gerrit-env-vars-restore@b728d1589228e2891a4241a1bba362d76895c225
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout VPP Gerrit Change
        uses: pmikus/vpp/.github/actions/vpp-checkout-gerrit-change@master
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          GERRIT_BRANCH: ${{ env.GERRIT_BRANCH }}
          GERRIT_REFSPEC: ${{ env.GERRIT_REFSPEC }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Install VPP dependencies
        uses: pmikus/vpp/.github/actions/vpp-install-deps@master
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Install VPP external dependencies
        uses: pmikus/vpp/.github/actions/vpp-install-ext-deps@master
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Build VPP
        uses: pmikus/vpp/.github/actions/vpp-build@master
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          MAKE_PARALLEL_JOBS: ${{ env.MAKE_PARALLEL_JOBS }}
          BUILD_TYPE: ${{ matrix['build_type'] }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Setup Docker VPP Runtime Environment for 'make test'
        uses: pmikus/vpp/.github/actions/vpp-docker-runtime-setup@master
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          SHM_SIZE: ${{ env.SHM_SIZE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: VPP Make Test
        uses: pmikus/vpp/.github/actions/vpp-make-test@master
        timeout-minutes: 90
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          TEST_JOBS: ${{ env.TEST_JOBS }}
          TEST_RETRIES: ${{ env.TEST_RETRIES }}
          MAKE_TEST_OS: ${{ env.MAKE_TEST_OS }}
          MAKE_TEST_MULTIWORKER_OS: ${{ env.MAKE_TEST_MULTIWORKER_OS }}
          VPPAPIGEN_TEST_OS: ${{ env.VPPAPIGEN_TEST_OS }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Report Success
        if: success()
        run: |
          echo "VPP Verify Make Test passed for Gerrit Refspec: $GERRIT_REFSPEC, Gerrit Change URL: $GERRIT_CHANGE_URL"
          echo "::notice::VPP Verify Make Test workflow completed successfully! Workflow ID: ${{ github.run_id }}, Name: ${{ github.workflow }}, Branch: $GERRIT_BRANCH, Change: $GERRIT_CHANGE_NUMBER, Patchset: $GERRIT_PATCHSET_NUMBER"
