name: vpp-vfy-hst

on:
  workflow_run:
    workflows: ["vpp-checkstyle"]
    types:
      - completed

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

concurrency:
  group: required-${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}-${{ github.event.workflow_run.id }}
  cancel-in-progress: true

jobs:
  vpp-verify-hst:
    name: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}-${{ matrix.build_type }}-${{ matrix.os }}-${{ matrix.executor_arch }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=hst
      - fdio:namespace=sandbox
      - fdio:os=${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu2404', 'ubuntu2204']
        executor_arch: ['x86_64', 'aarch64']
        build_type: ['dbg', 'rel']
        exclude:
          # Exclude ubuntu2404 OS for all builds on aarch64
          - os: 'ubuntu2404'
            executor_arch: 'aarch64'
          # Exclude release build ubuntu2404 OS on all architectures
          - build_type: 'release'
            os: 'ubuntu2404'

    env:
      CACHE_DATE: ${{ github.run_id }}
      CCACHE_DIR: /scratch/ccache/${{ matrix.os }}-${{ matrix.executor_arch }}
      MAKE_PARALLEL_JOBS: 16
      WORKSPACE: ${{ github.workspace }}
      HS_TEST_DIR: ${{ github.workspace }}/test-c/hs-test
      GERRIT_BRANCH: ""
      GERRIT_CHANGE_URL: ""
      GERRIT_PROJECT: ""
      GERRIT_REFSPEC: ""
      TUI_LINE: "*******************************************************************"

    steps:
      - name: Actions Checkout
        uses: actions/checkout@v5

      - name: "Show Nomad Attributes"
        uses: pmikus/.github/.github/actions/show-nomad-attributes@main

      - name: "Show Nomad Dockerfile"
        uses: pmikus/.github/.github/actions/show-nomad-dockerfile@main

      - name: Restore VPP Gerrit Environment Variables
        uses: pmikus/.github/.github/actions/gerrit-env-vars-restore@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Gerrit Checkout
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/checkout-gerrit-change-action@54d751e8bd167bc91f7d665dabe33fae87aaaa63 # v0.9
        with:
          gerrit-refspec: ${{ env.GERRIT_REFSPEC }}
          gerrit-project: ${{ env.GERRIT_PROJECT }}
          gerrit-url: ${{ env.GERRIT_CHANGE_URL }}
          ref: refs/heads/${{ env.GERRIT_BRANCH }}
          fetch-depth: 0
          delay: "0s"

      - name: Setup Environment
        uses: pmikus/.github/.github/actions/setup-executor-env@main

      - name: Install VPP dependencies
        uses: pmikus/vpp/.github/actions/vpp-install-deps@master

      - name: Install VPP external dependencies
        uses: pmikus/vpp/.github/actions/vpp-install-ext-deps@master

      - name: HST VPP Build
        uses: pmikus/vpp/.github/actions/vpp-build@master
        with:
          MAKE_PARALLEL_JOBS: ${{ env.MAKE_PARALLEL_JOBS }}
          BUILD_TYPE: ${{ matrix['build_type'] }}
          BUILD_HST: 'true'

      - name: HST Test VPP
        uses: pmikus/vpp/.github/actions/vpp-hst-test@master
        timeout-minutes: 60
        with:
          BUILD_TYPE: ${{ matrix['build_type'] }}
          HS_TEST_DIR: ${{ env.HS_TEST_DIR }}
          TUI_LINE: ${{ env.TUI_LINE }}
