name: vpp-vfy-hst

on:
  workflow_run:
    workflows: ["vpp-checkstyle"]
    types:
      - completed

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

concurrency:
  group: required-${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}-${{ github.event.workflow_run.id }}
  cancel-in-progress: true

jobs:
  vpp-vfy-hst:
    name: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}-${{ matrix.build_type }}-${{ matrix.os }}-${{ matrix.executor_arch }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=hst
      - fdio:namespace=dev
      - fdio:os=${{ matrix.os }}

    # TODO: modify the self-hosted agent to ensure hst class workflows are placed on nomad clients
    #       one at a time or on a per numa node basis to avoid resource contention
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu2404', 'ubuntu2204']
        executor_arch: ['x86_64', 'aarch64']
        build_type: ['dbg', 'rel']
        exclude:
          # Exclude all ubuntu2404 on aarch64
          - os: 'ubuntu2404'
            executor_arch: 'aarch64'
          # Exclude all release builds on ubuntu2404
          - os: 'ubuntu2404'
            build_type: 'rel'
          # Exclude release builds on aarch64 (ubuntu2204 only, since ubuntu2404+aarch64 already excluded)
          - os: 'ubuntu2204'
            executor_arch: 'aarch64'
            build_type: 'rel'

    env:
      WORKSPACE: /scratch/docker-build/vpp
      HS_TEST_DIR: /scratch/docker-build/vpp/test-c/hs-test
      CCACHE_DIR: /scratch/ccache/${{ matrix.os }}-${{ matrix.executor_arch }}
      MAKE_PARALLEL_JOBS: 16
      TEST_JOBS: 16
      GERRIT_BRANCH: ""
      GERRIT_CHANGE_URL: ""
      GERRIT_PROJECT: ""
      GERRIT_REFSPEC: ""
      GERRIT_CHANGE_NUMBER: ""
      GERRIT_PATCHSET_NUMBER: ""
      TUI_LINE: "*******************************************************************"

    steps:
      - name: Actions Checkout
        uses: actions/checkout@v5

      - name: Setup Environment
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/setup-executor-env@b728d1589228e2891a4241a1bba362d76895c225

      - name: Show Nomad Dockerfile
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/show-nomad-dockerfile@b728d1589228e2891a4241a1bba362d76895c225

      - name: Restore VPP Gerrit Environment Variables
        # yamllint disable-line rule:line-length
        uses: pmikus/.github/.github/actions/gerrit-env-vars-restore@b728d1589228e2891a4241a1bba362d76895c225
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout VPP Gerrit Change
        uses: pmikus/vpp/.github/actions/vpp-checkout-gerrit-change@master
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          GERRIT_BRANCH: ${{ env.GERRIT_BRANCH }}
          GERRIT_REFSPEC: ${{ env.GERRIT_REFSPEC }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Install VPP dependencies
        uses: pmikus/vpp/.github/actions/vpp-install-deps@master
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Install VPP external dependencies
        uses: pmikus/vpp/.github/actions/vpp-install-ext-deps@master
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: HST VPP Build
        uses: pmikus/vpp/.github/actions/vpp-build@master
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          MAKE_PARALLEL_JOBS: ${{ env.MAKE_PARALLEL_JOBS }}
          BUILD_TYPE: ${{ matrix['build_type'] }}
          BUILD_HST: 'true'
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Start Docker Daemon
        uses: pmikus/vpp/.github/actions/vpp-start-docker@master
        with:
          START_DOCKER_SCRIPT: start-docker.sh
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: HST Test VPP
        if: success()
        uses: pmikus/vpp/.github/actions/vpp-hst-test@master
        timeout-minutes: 90
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          BUILD_TYPE: ${{ matrix['build_type'] }}
          HS_TEST_DIR: ${{ env.HS_TEST_DIR }}
          TEST_JOBS: ${{ env.TEST_JOBS }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Report Success
        if: success()
        run: |
          echo "VPP Verify HST passed for Gerrit Refspec: $GERRIT_REFSPEC, Gerrit Change URL: $GERRIT_CHANGE_URL"
          echo "::notice::VPP Verify HST workflow completed successfully! Workflow ID: ${{ github.run_id }}, Name: ${{ github.workflow }}, Branch: $GERRIT_BRANCH, Change: $GERRIT_CHANGE_NUMBER, Patchset: $GERRIT_PATCHSET_NUMBER"
