name: vpp-csit-vfy-api

on:
  workflow_run:
    workflows: ["vpp-checkstyle"]
    types:
      - completed

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

concurrency:
  group: required-${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  vpp-csit-vfy-api:
    name: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}-rel-ubuntu2404-x86_64
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=x86_64
      - fdio:class=builder
      - fdio:namespace=dev
      - fdio:os=ubuntu2404

    env:
      WORKSPACE: /scratch/docker-build/vpp
      CSIT_DIR: /scratch/docker-build/csit
      GERRIT_BRANCH: ""
      GERRIT_CHANGE_URL: ""
      GERRIT_CHANGE_NUMBER: ""
      GERRIT_PATCHSET_NUMBER: ""
      GERRIT_PROJECT: ""
      GERRIT_REFSPEC: ""
      TUI_LINE: "*******************************************************************"

    steps:
      - name: Actions Checkout
        uses: actions/checkout@v5

      - name: Setup Environment
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/setup-executor-env@b728d1589228e2891a4241a1bba362d76895c225

      - name: "Show Nomad Dockerfile"
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/show-nomad-dockerfile@b728d1589228e2891a4241a1bba362d76895c225

      - name: Restore VPP Gerrit Environment Variables
        # yamllint disable-line rule:line-length
        uses: pmikus/.github/.github/actions/gerrit-env-vars-restore@b728d1589228e2891a4241a1bba362d76895c225
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout VPP Gerrit Change
        uses: pmikus/vpp/.github/actions/vpp-checkout-gerrit-change@master
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          GERRIT_BRANCH: ${{ env.GERRIT_BRANCH }}
          GERRIT_REFSPEC: ${{ env.GERRIT_REFSPEC }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Run CSIT check_crc.sh
        run: |
          set -euxo pipefail

          # Checkout CSIT HEAD
          cd $CSIT_DIR
          git checkout HEAD

          # Run check_crc.sh from CSIT
          cd $WORKSPACE
          # TODO: fix csit bash scripts to not rely on CSIT_DIR being inside WORKSPACE
          NEW_CSIT_DIR="$WORKSPACE/$(basename $CSIT_DIR)"
          mv $CSIT_DIR $NEW_CSIT_DIR
          csit_entry_dir="$NEW_CSIT_DIR/resources/libraries/bash/entry"
          source "${csit_entry_dir}/with_oper_for_vpp.sh" "check_crc.sh"

      - name: Report Success
        if: success()
        run: |
          echo "VPP CSIT API Check passed for Gerrit Refspec: $GERRIT_REFSPEC, Gerrit Change URL: $GERRIT_CHANGE_URL"
          echo "::notice::VPP CSIT API Check workflow completed successfully! Workflow ID: ${{ github.run_id }}, Name: ${{ github.workflow }}, Branch: $GERRIT_BRANCH, Change: $GERRIT_CHANGE_NUMBER, Patchset: $GERRIT_PATCHSET_NUMBER"
